project:
  type: website
  output-dir: docs

website:
  title: "Reach for Excellence"
  navbar:
    left:
      - href: index.qmd
        text: Lesson

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



